# Generated by Django 3.1.6 on 2021-02-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus',
            table='Add_Bus',
        ),
    ]
