# Generated by Django 3.1.6 on 2021-02-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210213_2201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Booking_Details',
        ),
    ]
