# Generated by Django 3.1.7 on 2021-02-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_book_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus'),
        ),
    ]
