# Generated by Django 3.1.6 on 2021-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210213_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='nos',
        ),
        migrations.AddField(
            model_name='book',
            name='useat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
