# Generated by Django 3.1.6 on 2021-02-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210223_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='busid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='source',
        ),
        migrations.RemoveField(
            model_name='book',
            name='userid',
        ),
    ]
